apiVersion: v1
kind: Secret
metadata:
  name: cert-passphrase
  namespace: default
type: Opaque
data:
  passphrase: bXlzZWNyZXRwYXNzcGhyYXNl
---
apiVersion: v1
kind: Secret
metadata:
  name: exported-cert
  namespace: default
type: kubernetes.io/tls
data: {}
---
apiVersion: acm.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: exportable-public-cert
  namespace: default
spec:
  domainName: guptadiv.people.aws.dev
  options:
    export: ENABLED
    certificateTransparencyLoggingPreference: DISABLED
  exportTo:
    secretName: exported-cert
    passphrase:
      secretName: cert-passphrase
      key: passphrase