apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: exported-cert-secret
  namespace: demo-app
data:
  tls.crt: ""
  tls.key: ""
---
apiVersion: acm.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: exportable-public-cert
  namespace: demo-app
spec:
  domainName: guptadiv.people.aws.dev
  options:
    certificateTransparencyLoggingPreference: ENABLED
  exportPassphrase: bXlzZWNyZXRwYXNzcGhyYXNl
  exportTo: 
    namespace: demo-app
    name: exported-cert-secret
    key: tls.crt
