apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: exported-cert-secret
  namespace: demo-app
data:
  tls.crt: ""
  tls.key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: passphrase-secret
  namespace: demo-app
data:
  passphrase: bXlzZWNyZXRwYXNzcGhyYXNl
---
apiVersion: acm.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: exportable-public-cert
  namespace: demo-app
spec:
  domainName: ${LOAD_BALANCER_HOSTNAME}
  options:
    certificateTransparencyLoggingPreference: ENABLED
  exportPassphrase:
    name: passphrase-secret
    namespace: demo-app
    key: passphrase
  exportTo: 
    namespace: demo-app
    name: exported-cert-secret
    key: tls.crt
